// COPIA GENERADA por scripts/sync-org-analytics.sh desde apps/web/src/lib/help.ts. No editar aquí.
// Explicaciones cortas para el signo ⓘ. Se buscan por el título o la etiqueta
// exacta de la tarjeta/página (sin tildes ni mayúsculas), así el texto vive en
// un solo lugar y aparece solo donde corresponde.
const HELP: Record<string, string> = {
  // ---- KPIs del organizador
  "ingresos netos": "Lo que te queda de las ventas pagadas después de restar la comisión de Plann y los descuentos. Es tu dinero real, no el total cobrado.",
  "entradas vendidas": "Cuántas entradas se han pagado. En un evento se muestra como vendidas / cupo total.",
  "saldo disponible": "Dinero ya liberado que puedes retirar hoy. Depende de tu plan: Básico se libera 3 días después del evento, Pro 3 días después de cada venta, Business en 24 horas.",
  "pedido promedio": "Lo que gasta en promedio cada comprador por pedido, antes de la comisión. Sube si vendes paquetes o entradas VIP.",
  "conversion de pedidos": "De cada 100 pedidos iniciados, cuántos terminan pagados. Baja si la gente reserva y no paga a tiempo (el pedido vence a los 15 minutos).",
  conversion: "Porcentaje de pedidos iniciados que terminaron pagados. Una conversión baja suele indicar problemas con el pago o el precio.",
  asistencia: "De las entradas de eventos ya terminados, cuántas se usaron en la puerta. Te dice cuánta gente que pagó realmente fue.",
  "visitas a tus eventos": "Personas que abrieron la página de alguno de tus eventos. Comparadas con las ventas te dicen si el evento convence.",
  visitas: "Personas que abrieron la página de este evento. Comparadas con las ventas te dicen cuántos visitantes terminan comprando.",
  seguidores: "Personas que te siguen y reciben aviso cuando publicas un evento nuevo. Es tu audiencia propia.",
  compradores: "Personas distintas que te han comprado. El porcentaje de recompra indica cuántas volvieron a comprar.",
  "eventos activos": "Eventos publicados que todavía no han terminado y están a la venta o en curso.",
  calificacion: "Promedio de las reseñas que dejan los asistentes después del evento (de 1 a 5 estrellas).",
  "sin responder": "Reseñas a las que todavía no has contestado. Responder públicamente mejora la confianza de futuros compradores.",
  // ---- Finanzas
  "disponible para retirar": "Saldo ya liberado según tu plan. Puedes pedir un retiro por este monto o menos (mínimo $5).",
  "por liberar": "Ventas pagadas que aún no cumplen el plazo de tu plan. Pasan a «disponible» solas cuando llega la fecha.",
  "en proceso de pago": "Retiros que ya pediste y Plann todavía no ha transferido. Ese dinero ya no cuenta como disponible.",
  "ya retirado": "Total que Plann ya te transfirió en retiros anteriores.",
  "por reembolsar": "Compras de eventos cancelados que hay que devolver al comprador. Ya están descontadas de tu saldo.",
  "venta bruta": "Total cobrado por las entradas a precio de lista, sin restar comisión ni descuentos.",
  "comision plann": "Porcentaje que Plann retiene de cada venta según tu plan: Básico 12 %, Pro 8 %, Business 6 %. Se calcula sobre lo que el comprador realmente paga.",
  "neto para ti": "Venta bruta menos descuentos y comisión de Plann. Es lo que se acredita a tu saldo.",
  "solicitar retiro": "Pide que Plann te transfiera tu saldo disponible a la cuenta que configuraste. Se paga en 1 a 2 días hábiles.",
  "solicitudes de retiro": "Retiros pedidos por los organizadores. Marca cada uno como pagado cuando hagas la transferencia.",
  "historial de retiros": "Todos tus retiros y en qué estado está cada uno: pendiente, pagado o rechazado.",
  "liquidacion por evento": "Cómo se reparte el dinero de cada evento: bruto, descuentos, comisión de Plann, reembolsos y lo que te queda.",
  "liquidacion del evento": "Cómo se reparte el dinero de este evento: bruto, descuentos, comisión de Plann, reembolsos y lo que te queda.",
  "resumen por mes": "Ventas pagadas, comisión y neto agrupados por mes. Útil para tu contabilidad.",
  // ---- Gráficos y analíticas
  "ventas por dia": "Ingresos netos (área) y entradas vendidas (línea) día a día. Sirve para ver el efecto de una promoción o publicación.",
  "evolucion de ventas": "Entradas vendidas acumuladas desde que abriste las ventas. Una curva plana avisa que hay que promocionar.",
  "visitas por dia": "Cuánta gente abrió tu evento cada día. Si sube y las ventas no, revisa precio y descripción.",
  "por tipo de entrada": "Cuánto vendió y recaudó cada tipo de entrada. Te dice cuál prefiere tu público.",
  "ingresos por tipo de entrada": "Dinero neto que dejó cada tipo de entrada a lo largo del tiempo.",
  "ingresos por evento": "Ingresos netos de cada evento en el periodo elegido.",
  "ingresos netos por evento": "Lo que te dejó cada evento después de comisión y descuentos.",
  "cuando compran": "Entradas vendidas por día de la semana. Úsalo para elegir cuándo publicar o lanzar ofertas.",
  "como pagan tus compradores": "Reparto de las ventas por método de pago (Pago Móvil, transferencia, Zelle).",
  "llegada de asistentes": "Entradas validadas en la puerta por hora. Te ayuda a dimensionar el personal de puerta.",
  comparativa: "Tus eventos lado a lado, ordenados por ingresos. Compara ventas, cupo lleno y conversión.",
  "comparar eventos": "Compara tus eventos: cuál vende más, cuál llena el cupo y cuál convierte mejor las visitas en compras.",
  "por evento": "Reparto de ventas entre tus eventos.",
  "proximos eventos": "Tus próximos eventos a la venta y qué tan avanzadas van las ventas de cada uno.",
  // ---- Eventos y operación
  eventos: "Todos tus eventos: publicados, borradores y pasados. Desde aquí editas, pausas, duplicas o repites cada uno.",
  "nuevo evento": "Crea un evento con sus entradas. Se publica al guardar (o en la fecha que programes) y aparece de inmediato en la app.",
  entradas: "Los tipos de entrada del evento con su precio, cupo y fechas de venta. Lo ya vendido no cambia si editas.",
  ventas: "Todos los pedidos de tus eventos y lo que te queda de cada uno después de la comisión de Plann. Puedes filtrar y reembolsar.",
  asistentes: "Quiénes compraron y quién ya entró. Aquí también invitas gente y les escribes.",
  "avisar a los asistentes": "Envía un mensaje a todos los que tienen entrada (cambio de hora, lugar u otra novedad). Llega como notificación. Máximo 3 al día.",
  "invitar a alguien": "Regala entradas de cortesía por correo. Si la persona aún no tiene cuenta, las recibe al registrarse. No cuentan como venta ni generan comisión.",
  "repetir este evento": "Crea copias del evento cada semana o cada mes con las mismas entradas. Salen como borradores para que las revises.",
  "cancelar evento": "Cierra las ventas, avisa a los compradores y deja las compras pagadas por reembolsar. No se puede deshacer.",
  "ventas por metodo de pago": "Cuánto se cobró por cada método de pago.",
  "ventas por ciudad": "De qué ciudades vienen las ventas.",
  "ventas por categoria": "Qué categorías de evento venden más.",
  pedidos: "Cada compra: quién, cuánto pagó y en qué estado está. Puedes reembolsar las pagadas.",
  "ultimos pedidos": "Las compras más recientes de tus eventos.",
  "pedidos del evento": "Compras de este evento y su estado. Desde aquí puedes reembolsar.",
  "ordenes de este evento": "Compras de este evento y su estado.",
  "ordenes recientes": "Las compras más recientes en Plann.",
  "historial de ordenes": "Todas las compras de esta cuenta y su estado.",
  // ---- Crecimiento
  cupones: "Códigos de descuento (porcentaje o monto fijo) para tus compradores. Tú absorbes la rebaja; la comisión se calcula sobre lo que realmente pagan.",
  "crear cupon": "Define el código, el descuento, los usos máximos y hasta cuándo vale. Puede ser para un evento o para todos.",
  "tus cupones": "Tus códigos y cuántas veces se han usado. Puedes pausarlos o borrarlos.",
  resenas: "Lo que dicen quienes asistieron. Tus respuestas son públicas y se ven junto a la reseña.",
  "todas las resenas": "Todas las reseñas de tus eventos. Responde para mostrar que cuidas a tu público.",
  reportes: "Descarga tus ventas en CSV, listas para Excel o para tu contador.",
  // ---- Equipo y cuenta
  equipo: "Personas que te ayudan. Puerta solo valida entradas; Editor gestiona eventos, cupones y mensajes; Finanzas solo ve dinero y reportes.",
  "agregar persona": "Invita por correo y elige su rol. Si aún no tiene cuenta, entra al equipo sola al registrarse. Tu plan limita cuántas personas puedes tener.",
  "tu equipo": "Quién está en tu equipo y con qué rol. Quitar a alguien le retira el acceso al instante.",
  configuracion: "Tu perfil público (logo, nombre, descripción) y la cuenta donde recibes tus pagos.",
  "perfil del negocio": "Lo que ve el público en tu página de organizador y en cada evento.",
  "tu cuenta": "Tu plan, comisión y estado de verificación.",
  "ayuda y soporte": "Preguntas frecuentes y contacto directo con el equipo de Plann. Respondemos de 8 a. m. a 12 a. m.",
  "tus consultas": "Tus mensajes a soporte y su estado. Te avisamos cuando respondemos.",
  "escribirle a plann": "Cuéntanos tu problema con el mayor detalle posible (evento, monto, fecha) para resolverlo más rápido.",
  "preguntas frecuentes": "Respuestas a las dudas más comunes. Revísalas antes de escribir.",
  // ---- Herramientas y pantallas de la app del organizador
  "publicar evento": "Crea un evento con sus entradas y ponlo a la venta. Puedes programarlo para que salga solo en una fecha.",
  "escanear entradas": "Valida los QR de los asistentes en la puerta con la cámara del teléfono, o escribe el código PLN-XXXXXX si el QR no abre. Cada entrada solo entra una vez.",
  "mis eventos": "Tus eventos por estado. Desde cada tarjeta: analíticas, asistentes, editar, escanear, ofertas, duplicar, repetir y compartir.",
  "ventas y pedidos": "Cada compra con su estado y lo que te queda después de la comisión. Puedes filtrar y reembolsar las pagadas.",
  "retiros y saldo": "Tu dinero: lo disponible para retirar, lo que aún se libera según tu plan y tus solicitudes de retiro.",
  "retiros y finanzas": "Tu dinero: lo disponible para retirar, lo que aún se libera según tu plan y tus solicitudes de retiro.",
  "equipo y roles": "Personas que te ayudan. Puerta solo valida entradas; Editor gestiona eventos, cupones y mensajes; Finanzas solo ve dinero y reportes.",
  "mi negocio": "Tu perfil público (logo, nombre, descripción) y la cuenta donde recibes tus pagos.",
  "conviertete en organizador": "Para publicar eventos y vender entradas verificamos quién eres. Revisamos tu solicitud en menos de 24 horas.",
  "editar evento": "Cambia los datos del evento. Las entradas ya vendidas no se alteran; para precios y cupos usa la sección Entradas.",
  "analiticas del evento": "Cómo va este evento: ventas, visitas, conversión, asistencia y liquidación. Toca cada gráfico para entender qué mide.",
  "ofertas y comunidad": "Configura la oferta de última hora de cada entrada y marca el evento como comunitario para que salga en la portada.",
  "modo puerta": "Vista para el personal de puerta: solo los eventos próximos y el escáner, sin ventas ni compradores.",
  "mi cumpleanos": "Plann te regala 10 % (hasta $5) en una compra durante los 3 días antes y después de tu cumpleaños, una vez al año. Solo tú ves tu fecha.",
  "regalar entrada": "Envía tu entrada a otra persona por correo. Tu QR deja de funcionar y le llega uno nuevo a ella. Si no tiene cuenta, la recibe al registrarse.",
  "mi nivel y puntos": "Cada compra suma puntos y subes de nivel. Los niveles altos dan ventajas como preventas anticipadas.",
  "historial de compras": "Todas tus compras y su estado.",
  "calificar evento": "Cuenta cómo estuvo el evento. Tu reseña ayuda a otros compradores y el organizador puede responderla.",
  consulta: "Tu conversación con soporte. Responde aquí y te avisamos cuando contestemos.",
  // ---- Admin
  dashboard: "Vista general de Plann: ventas, ingresos, pagos por verificar y salud del negocio. Lo primero que conviene revisar cada día son los pagos por verificar y los retiros pendientes.",
  gmv: "Gross Merchandise Value: el total vendido en entradas (bruto) en el periodo, antes de restar comisiones. Mide el tamaño del negocio, no lo que gana Plann.",
  "conversion de checkout": "De cada 100 personas que empiezan a pagar, cuántas completan la compra. Si baja, revisa métodos de pago y tiempos de verificación.",
  "pagos por verificar": "Pagos que el comprador dice haber hecho y aún no has confirmado con tu banco. Mientras esperan, el comprador no recibe sus entradas.",
  "cola de verificacion manual": "Pagos que requieren tu revisión. Compara la referencia y el monto con tu banco y aprueba o rechaza; al aprobar, las entradas se emiten solas.",
  notificaciones: "Avisos de tu operación: ventas, cupos por agotarse, retiros y mensajes de soporte.",
  finanzas: "Tu saldo, tus retiros y cuánto te queda de cada venta. Aquí pides que Plann te transfiera tu dinero.",
  compartir: "Enlace público y QR de tu evento para redes y afiches. Medimos las visitas de cada vía para que sepas cuál funciona.",
  "pasivo total con organizadores": "Todo el dinero disponible que Plann le debe hoy a los organizadores. Es lo que necesitas tener listo para pagar retiros.",
  "retiros pendientes de aprobar": "Monto de retiros pedidos que aún no has pagado ni rechazado.",
  "retiros pendientes": "Retiros pedidos por organizadores que faltan por pagar.",
  "organizadores con saldo": "Organizadores que tienen dinero disponible para retirar.",
  "ingresos de plann": "Lo que gana Plann: comisiones a organizadores más el fee de servicio que paga el comprador.",
  "compradores nuevos": "Compradores que hicieron su primera compra en el periodo.",
  "organizadores activos": "Organizadores verificados que tienen eventos en Plann.",
  "eventos publicados": "Eventos a la venta ahora. Los «en revisión» esperan tu aprobación.",
  "retiros y liquidaciones": "Lo que Plann le debe a cada organizador y las solicitudes de retiro para pagar.",
  retiros: "Marca como pagado cuando hayas hecho la transferencia al organizador; el sistema descuenta su saldo.",
  usuarios: "Compradores registrados. Busca por nombre, correo, teléfono o cédula y revisa su historial.",
  soporte: "Consultas de compradores y organizadores. Las de organizadores Business van primero.",
  abiertos: "Consultas nuevas que todavía nadie ha atendido.",
  "en proceso": "Consultas que ya se están atendiendo.",
  prioritarios: "Consultas de organizadores de plan Business o marcadas como urgentes.",
  resueltos: "Consultas ya cerradas con respuesta.",
  consultas: "Todas las consultas recibidas. Abre una para responder o cambiar su estado.",
  "registro de auditoria": "Bitácora inmutable de toda acción administrativa: quién hizo qué y cuándo. No se puede editar ni borrar.",
  organizadores: "Verificación, plan, ventas y salud de cada negocio. Desde aquí suspendes o cambias el plan.",
  "verificacion de organizadores": "Solicitudes de personas que quieren vender en Plann. Revisa su documento y apruébalas o recházalas con un motivo.",
  "eventos y moderacion": "Cola de revisión y catálogo de eventos. Modera lo que no cumpla las reglas.",
  "banderas de funciones": "Interruptores para activar métodos de pago o secciones sin publicar una versión nueva de la app.",
  "cuentas receptoras": "Cuentas de Plann que ven los compradores para pagar. Se rotan para repartir los depósitos.",
  "comision por plan": "Porcentaje que cobra Plann según el plan del organizador. Aplica solo a órdenes nuevas.",
  "equipo plann": "Personas del equipo de Plann con acceso al admin y su autenticación de dos factores.",
  "gmv por dia": "GMV: total vendido (bruto) por día en Plann, sin restar comisiones. Mide el tamaño del negocio.",
  "ingresos de plann por via": "De dónde salen los ingresos de Plann: comisiones, fees de servicio u otros.",
  "pagos y conciliacion": "Pagos que los compradores dicen haber hecho. Concilia la referencia con tu banco y aprueba o rechaza.",
  solicitudes: "Solicitudes de organizadores pendientes de revisión.",
  "reembolsos por cancelacion": "Eventos cancelados con pagos que hay que devolver a los compradores.",
};

function normalize(s: string): string {
  return s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").trim();
}

export function getHelp(label: string | undefined): string | undefined {
  return label ? HELP[normalize(label)] : undefined;
}

export const HELP_KEYS = Object.keys(HELP);
